# infrastructure/local/livekit.yaml
# Minimal LiveKit configuration for local development
port: 7880

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false

redis:
  address: voice-doc-redis:6379
  password: voicedoc123

turn:
  enabled: false

room:
  auto_create: true
  empty_timeout: 300
  max_participants: 100

keys:
  APIXjm39Ra3J5e2: z9vkfnS7YzWkzEjtzjDxmgxgu45i20P4ki61Vm3u4eT

logging:
  level: info
  sample: false